version: '3.8'

services:
  agent:
    build:
      context: ./microservices/Agent
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./microservices/Agent:/app
      - ./microservices/Agent/.env:/app/.env
    environment:
      - ENVIRONMENT=development
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=agent_db
      - COLLECTION_NAME=agents
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 